### PR TITLE
405 writing

### PR DESCRIPTION
**Pull request by jingyilong**
Everything should be good to merge. I updated TemporalOrientation although as a note its definition and connection to SettingType may need to change.

### CODE REVIEW

**Comment by alliyya** [comment]
@jingyilong I've updated the pre-testing version: https://sparql.cwrc.ca/github/ontology/cwrc.html

If you want to review it before I do a deeper review?

**Comment by jingyilong** [comment]
@alliyya It looks good to me.

**Comment by alliyya** [comment]
Still need to review the following:
- [ ] remove empty altLabels/definitions
    - [ ] May have to adjust the script to not generate placeholder definitions "This is the inverse of {LABEL}, whose definition is as follows:"
- [ ] top lvl classes should be owl:Class and skos:conceptSchemes
- [ ] Review hiearchies
- [ ] Review properties names (foaf, rdf, rdfs, skos ...)
  - [ ] rdf:literal --> rdfs:Literal
- [ ] update version information
- [ ] update contributors

**Comment by alliyya** [comment]
@jingyilong Here are some really long diagrams of hierarchies, If you zoom in enough they do get more clear, and if you hover on the node they should show the URI.

[classes.pdf](https://github.com/cwrc/ontology/files
[properties.pdf](https://github.com/cwrc/ontology/files/12088542/properties.pdf)
/12088510/class.pdf)

Let me know if you want more specific property trees or you notice some weird ommissions.

**Comment by jingyilong** [comment]
Notes to resolve 

- label of motif is topic type
- foaf:accountName is broader of system name -- double check its use
- sem:EventType and sem:Event are also used in the vocab -- @alliyya should it be used there?
- literary award is not attached to anything -- attach to educational organization?

floating classes:
- lost literary work (bf:work)
- author name type (under name type or authorial name?)
- authorship controversy
- birth position
- change set
- credential (under educational organization)
- destruction type
- educational subject
- educational text
- fellowship
- occupation
- oeuvre
- publication mode
- reproductive history
- textual label

**Comment by alliyya** [comment]
> Notes to resolve for classes
> 
> * [x]  label of motif is topic type
> * foaf:accountName is broader of system name -- double check its use
> * sem:EventType and sem:Event are also used in the vocab -- @alliyya should it be used there?
> * literary award is not attached to anything -- attach to educational organization?
> 
> floating classes: (+possible broader classes)
> 
> * [ ]  lost literary work (bf:work)
> * [x]  author name type (NameType)
> * [x]  authorship controversy (ResponseContext)
> * [ ]  birth position
> * [ ]  change set
> * [ ]  credential (under educational organization)
> * [ ]  destruction type
> * [ ]  educational subject
> * [ ]  educational text
> * [x]  fellowship (educationalAward)
> * [ ]  occupation
> * [ ]  oeuvre
> * [x]  publication mode (PublishingContext)
> * [ ]  reproductive history
> * [ ]  textual label


Is sem:EventType and sem:Event used in different contexts? 


Generally note that some detached classes/properties is to be expected. It's not wrong.

**Comment by jingyilong** [comment]
> As for biography:Type, I'm not quite sure? Are all top concepts of the other split up vocabs narrower than biography:Type? How are they relating to the other vocabs?

The type top concept was more of a catch-all term in the cwrc vocab, but since most of its narrower terms are related to biography I included it in biography.ttl as a top concept. `eventClimate` and `eventSignificance` were narrower terms but since they relate closely to event I pulled them out and changed them to top concepts of event.ttl. `occupation:occupationType` is also similar: a top concept in occupation.ttl but has `biography:type` as a broader term.

**Comment by jingyilong** [comment]
@alliyya I reviewed all the property names and I didn't see any errors. Is there anything else to do before this is merged?

**Pull request merged**
